Fetch name from PDL
navikt/tms-utbetalingsoversikt-frontend pull request #53
Opened 2024-11-12 12:00 UTC by nima-hakimi

- **Fetch name from PDL**
- **Correct getOboToken**
- **Delete min-side**
- **Talk to PDL**
- **console.log pdl response**
- **console.log**
- **...**
- **Pdl can talk to us**
- **Debugging**
- **Add correct fetch url and mock data in frontend**
- **Add bnr**
- **Cleanup**
- **Remove useless await**
- **Set token to be an empty string when local**
- **Setup jose for mocking token locally and remove behandlingsnr to check error message from pdl**
- **Håndter error fra pdl**
- **Write tests for pdl fetch and refactor mock data**
- **Correct syntaxError in workflow file**
- **Try correcting workflow file**
- **Try correcting workflows**
- **Coment out anv**
- **Coment out test completely**
- **Try Erasing whitespace in run**
- **add sleep command in workflows**
- **Remove sleep and check if the job still runs**
- **remove used coment from gh workflows**

2024-11-12 12:13 UTC, Amirhlotfi requested changes

2024-11-12 12:13 UTC, Amirhlotfi commented on src/utils/client/urls.ts
>  const IDENT_NAVN_URL = {
Navnet hentes fortsatt fra gammel endepunkt i dev

2024-11-12 12:42 UTC, sasoria commented on src/utils/server/token.ts
> +const audience = 'dev-fss:pdl:pdl-api';
Audience må også støtte prod-fss

2024-11-13 08:32 UTC, Amirhlotfi commented on src/utils/client/urls.ts
> +  production: 'https://www.nav.no/api/navn',
Dette blir feil url. Prøv https://www.nav.no/utbetalingsoversikt/api/navn

2024-11-18 09:53 UTC, sasoria approved these changes

2024-11-18 10:02 UTC, Amirhlotfi approved these changes

2024-11-18 10:03 UTC, merged