SSR page 2
navikt/tms-utbetalingsoversikt-frontend pull request #61
Opened 2024-12-12 09:18 UTC by nima-hakimi

SSR entire page 2. Future work is to modify the file structure

2024-12-13 09:03 UTC, nima-hakimi commented
@Amirhlotfi Hvor er kommentarer

2024-12-13 09:03 UTC, Amirhlotfi requested changes

2024-12-13 09:06 UTC, Amirhlotfi commented on src/components/pages/utbetalingDetaljeSide/UtbetalingPage.astro
> +<Heading level="1" size="xlarge">{enkelUtbetaling.ytelse}</Heading>
Denne skal ikke vises ved print

2024-12-13 09:07 UTC, Amirhlotfi requested changes

2024-12-13 09:07 UTC, Amirhlotfi commented on src/components/pages/utbetalingDetaljeSide/UtbetalingPage.astro
> +<Heading level="1" size="xlarge">{enkelUtbetaling.ytelse}</Heading>
Denne skal ikke vises ved print

2024-12-16 06:50 UTC, Amirhlotfi approved these changes
Nice 🚀

2024-12-16 09:51 UTC, merged